[AMQP]

# Host information
host = "amqp.example.com"
vhost = "vhost"

# Username and password for the AMQP router
username = "amqpusername"
password = "amqppassword"

exchange = 'gracc.osg.requests'
queue = 'gracc.osg.requests'

[ElasticSearch]
raw_index = 'gracc.osg.raw0-*'
raw_type = 'JobUsageRecord'
