[AMQP]

# Host information
# scheme://username:password@host:port/vhost
url = "amqps://amqpusername:amqppassword@amqp.exapmle.com:5671/vhost"

exchange = 'gracc.osg.requests'
queue = 'gracc.osg.requests'

[ElasticSearch]
uri = 'http://localhost:9200'
raw_index = 'gracc.osg.raw-*'
raw_type = 'JobUsageRecord'
transfer_type = 'Storage'
transfer_index = 'gracc.osg-transfer.raw-*'

[[Corrections]]
index = 'gracc.corrections'
doc_type = 'vo'
match_fields = ['VOName','ReportableVOName']
source_field = 'CorrectedVOName'
dest_field = 'VOName'

[[Corrections]]
index = 'gracc.corrections'
doc_type = 'project'
match_fields = ['ProjectName']
source_field = 'CorrectedProjectName'
dest_field = 'ProjectName'

[[Corrections]]
index = 'gracc.corrections'
doc_type = 'host_description_regex'
match_fields = ['Host_description']
source_field = 'CorrectedHostDescription'
dest_field = 'OIM_Site'
regex = true

[OIM_URLs]
voinfo = 'https://my.opensciencegrid.org/vosummary/xml?active=on&active_value=1&oasis_value=1'
oimtopology = 'https://my.opensciencegrid.org/rgsummary/xml?facility_sel%5B%5D=10009&gridtype=on&gridtype_1=on&active=on&active_value=1&disable_value=1'
projects = 'https://my.opensciencegrid.org/miscproject/xml'
